version: "3"

services: 
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=gartic
    ports:
      - 7568:5432
    volumes: 
      - ./postgres-data:/var/lib/database/data
      # - ./postgres/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
    networks:
      - gartic_deployment

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./gartic-go-backend
    depends_on: 
      postgres:
        condition: service_started
    ports:
      - 8000
      - 5555
    environment:
      - GO_ENV=production
    networks:
      - gartic_deployment
  
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./gartic-like-app
    ports:
      - 3333:3333
      - 5555:5555
      - 8000:8000
    depends_on: 
      backend:
        condition: service_started
    networks:
      - gartic_deployment   

networks:
  gartic_deployment:
    driver: bridge

volumes:
  postgres-data: 